- name: Create ZIP
  run: |
    cd ..
    zip -r wp-twilio-notification.zip wp-twilio-notification \
      -x "wp-twilio-notification/.git/*" \
      -x "wp-twilio-notification/.github/*" \
      -x "wp-twilio-notification/.gitignore"

- name: Upload Release
  uses: softprops/action-gh-release@v1
  with:
    files: ../wp-twilio-notification.zip